apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omni-infra-provider-hetzner.fullname" . }}
  labels:
    {{- include "omni-infra-provider-hetzner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "omni-infra-provider-hetzner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "omni-infra-provider-hetzner.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "omni-infra-provider-hetzner.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config-file=/config/hetzner.yaml
            - --provider-name={{ .Values.provider.name }}
            - --id={{ .Values.provider.id }}
            - --provider-description={{ .Values.provider.description }}
            {{- if .Values.provider.insecureSkipVerify }}
            - --insecure-skip-verify
            {{- end }}
          env:
            - name: OMNI_ENDPOINT
              value: {{ required "omni.apiEndpoint is required" .Values.omni.apiEndpoint | quote }}
            - name: OMNI_SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "omni-infra-provider-hetzner.secretName" . }}
                  key: omniServiceAccountKey
          volumeMounts:
            - name: hetzner-config
              mountPath: /config
              readOnly: true
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: hetzner-config
          secret:
            secretName: {{ include "omni-infra-provider-hetzner.secretName" . }}
            items:
              - key: hetznerConfig
                path: hetzner.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
