{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-infra-provider-hetzner.fullname" . }}
  labels:
    {{- include "omni-infra-provider-hetzner.labels" . | nindent 4 }}
type: Opaque
stringData:
  omniServiceAccountKey: {{ required "omni.serviceAccountKey is required when existingSecret is not set" .Values.omni.serviceAccountKey | quote }}
  hetznerConfig: {{ required "hetznerConfig is required when existingSecret is not set" .Values.hetznerConfig | quote }}
{{- end }}
